function [cph] = set_to_default(cph)
    cph.cp.minADCPoints = 0;
    cph.cp.minChirpLoops = 0;
    cph.cp.minRangeFFTSize = 0;
    cph.cp.minDopplerFFTSize = 0;
    cph.cp.maxADCPoints = 0;
    cph.cp.maxChirpLoops = 0;
    cph.cp.maxRangeFFTSize = 0;
    cph.cp.maxDopplerFFTSize = 0;
    cph.cp.staticClutterRemoval = true;
    cph.cp.startFrequency_MHz = 77e3;
    cph.cp.bandWidth_MHz = 3e3;
    cph.cp.idleTime_us = 20;
    cph.cp.rampTime_us = 100;
    cph.cp.periodicity_ms = 10;
    cph.cp.ADCPoints = 256;
    cph.cp.sampleRate_ksps = 3000;
    cph.cp.ADCDelay_us = 10;
    cph.cp.chirpLoops = 64;
    cph.cp.iqSample = true;
    cph.cp.antTDM = 1;
    cph.cp.rx = 1;
    cph.cp.rangeFFTSize = cph.cp.ADCPoints;
    cph.cp.dopplerFFTSize = cph.cp.chirpLoops;
    cph.cp.cfar.cfarEnabled = false;
    cph = compute_and_validate(cph);
end